edited yml

diff --git a/.github/workflows/operator-integration-test.yml b/.github/workflows/operator-integration-test.yml
--- a/.github/workflows/operator-integration-test.yml
+++ b/.github/workflows/operator-integration-test.yml
@@ -87,17 +87,25 @@ jobs:
                 cd -
                 make deploy
                 cd integration-tests/terraform/testbuild
-                kubectl apply -f ns-annotation-test-deployment.yaml
-                kubectl apply -f sample-instrumentation.yaml
-                kubectl apply -f test-deployment.yaml
+                kubectl apply -f ./sample-instrumentation.yaml
+                sleep 10
+                kubectl apply -f ./test-deployment.yaml
+                kubectl apply -f ./ns-annotation-test-deployment.yaml
                 sleep 60
-                kubectl describe pod
-                kubectl describe deploy -n amazon-cloudwatch
-                kubectl get pod -A
                 kubectl get all -n amazon-cloudwatch
-                kubectl get crd
-            else
-              terraform destroy -auto-approve && exit 1
+                kubectl get pods -A
+                kubectl describe deployment amazon-cloudwatch-observability-controller-manager -n amazon-cloudwatch
+                kubectl describe deployment nginx -n amazon-cloudwatch
+                kubectl describe deployment nginx
+                pod_name="$(kubectl get pods -n amazon-cloudwatch -l app.kubernetes.io/component=amazon-cloudwatch-agent,app.kubernetes.io/instance=amazon-cloudwatch.cloudwatch-agent -o=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}')"
+                status=$(kubectl get pod "$pod_name" -n amazon-cloudwatch -o=jsonpath='{.status.phase}')
+                if [ "$status" != "Running" ]; then
+                    echo "Pod $pod_name is not running. Exiting with ERROR."
+                    echo "Testcase 1: Pod running test case: FAIL"
+                    terraform destroy  -auto-approve && exit 1
+                else
+                    echo "Pod $pod_name is running."
+                    echo "Testcase 1: Pod running test case: PASS"
             fi
 
       - name: java Annotation testing
